# **Практика: обратная матрица, определитель, ранг**

In [1]:
import numpy as np

In [2]:
# обратная матрица - все ок
A1=np.array([[1,2,3],[4,5,6],[7,8,10]])
print('A1:\n',A1)

A1:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]


In [3]:
print('rk(A3):\n',np.linalg.matrix_rank(A1))

rk(A3):
 3


In [4]:
# обратная матрица - все ок
A1_inv=np.linalg.inv(A1)
print('A1 inversed:\n',A1_inv)


A1 inversed:
 [[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]


In [5]:
# обратная матрица - все ок
print('A1 @ A1 inversed=E check:\n',A1@A1_inv,1)
print(np.round(A1@A1_inv,1))
print('check OK')

A1 @ A1 inversed=E check:
 [[1.00000000e+00 0.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00 2.22044605e-16]
 [8.88178420e-16 0.00000000e+00 1.00000000e+00]] 1
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
check OK


In [6]:
# обратная матрица - вырожденный случай
A2=np.array([[1,2,3],[4,5,6],[1,2,3]])
print('A2:\n',A2)

A2:
 [[1 2 3]
 [4 5 6]
 [1 2 3]]


In [7]:
# обратная матрица - вырожденный случай
print('rk(A3):\n',np.linalg.matrix_rank(A2))

rk(A3):
 2


In [8]:
# обратная матрица - вырожденный случай
#np.linalg.inv(A2)

LinAlgError: Singular matrix

In [9]:
# обратная матрица - magic
A3=np.array([[1,2,3],[4,5,6],[7,8,9]])
print('A3:\n',A3)

A3:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
# обратная матрица - magic
print('rk(A3):\n',np.linalg.matrix_rank(A3))

rk(A3):
 2


In [12]:
# обратная матрица - magic
#print('A3 inversed:\n',np.linalg.inv(A3))

In [23]:
# обратная матрица - magic
#print('A3 @ A3 inversed = E check:\n',A3@np.linalg.inv(A3))
print('check failed')

check failed


In [14]:
print('det(A1)):\n',np.linalg.det(A1))

det(A1)):
 -2.9999999999999996


In [15]:
print('det(A2)):\n',np.linalg.det(A2))

det(A2)):
 0.0


In [16]:
print('det(A3)):\n',np.linalg.det(A3))

det(A3)):
 0.0


In [17]:
# обратная матрица - неустойчивость
A4=np.array([[1,2,3],[4,5,6],[1,2,3.00005]])
print('A4:\n',A4)
print('rk(A4):\n',np.linalg.matrix_rank(A4))
print('det(A4):\n',np.linalg.det(A4))
print('A4 inverse:\n',np.linalg.inv(A4))

A4:
 [[1.      2.      3.     ]
 [4.      5.      6.     ]
 [1.      2.      3.00005]]
rk(A4):
 3
det(A4):
 -0.00014999999999965044
A4 inverse:
 [[-2.00016667e+04  6.66666667e-01  2.00000000e+04]
 [ 4.00013333e+04 -3.33333333e-01 -4.00000000e+04]
 [-2.00000000e+04  0.00000000e+00  2.00000000e+04]]


In [18]:
# обратная матрица - неустойчивость вблизи нулевого определителя
A5=np.array([[1,2,3],[4,5,6],[1,2,3.00000005]])
print('A5:\n',A5)
print('rk(A5):\n',np.linalg.matrix_rank(A5))
print('det(A5):\n',np.linalg.det(A5))
print('A5 inverse:\n',np.linalg.inv(A5))

A5:
 [[1.         2.         3.        ]
 [4.         5.         6.        ]
 [1.         2.         3.00000005]]
rk(A5):
 3
det(A5):
 -1.5000000042064706e-07
A5 inverse:
 [[-2.00000016e+07  6.66666667e-01  1.99999999e+07]
 [ 4.00000012e+07 -3.33333333e-01 -3.99999999e+07]
 [-1.99999999e+07  0.00000000e+00  1.99999999e+07]]


In [19]:
# обратимость матрицы Грама линейно независимой системы векторов
v1=np.array([1,2,1])
v2=np.array([1,1,1])
A=np.array([v1,v2]).T
print('A:\n',A)
print('Матрица Грама:\n',A.T@A)

A:
 [[1 1]
 [2 1]
 [1 1]]
Матрица Грама:
 [[6 4]
 [4 3]]


In [20]:
print('Ранг матрицы Грама:\n',np.linalg.matrix_rank(A.T@A))

Ранг матрицы Грама:
 2


In [21]:
print('Определитель матрицы Грама:\n',np.linalg.det(A.T@A))

Определитель матрицы Грама:
 2.0000000000000004


In [22]:
print('Обратная к матрице Грама:\n',np.linalg.inv(A.T@A))

Обратная к матрице Грама:
 [[ 1.5 -2. ]
 [-2.   3. ]]


Дана матрица A:

Найдите матрицу, обратную матрице A.

В качестве ответа запишите элемент из первого столбца второй строки, округлив его до трёх знаков после точки-разделителя.

In [30]:
A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])

inv = np.linalg.inv(A)
print(inv)
print(inv[1,0].round(3))

[[-1.875    2.3125  -0.03125]
 [ 0.375   -0.5625   0.15625]
 [ 1.25    -1.375   -0.0625 ]]
0.375


Дана система векторов:

v1 = np.array([9, 10, 7, 7, 9])  
v2 = np.array([2, 0, 5, 1, 4])  
v3 = np.array([4, 0, 0, 4, 1])  
v4 = np.array([3, -4, 3, -1, -4])  

In [31]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])

Найдите ранг системы векторов. Для этого создайте матрицу системы векторов. Векторы в матрице расположите в столбцы.

In [37]:
A = np.array([v1, v2, v3, v4]).T
print(np.linalg.matrix_rank(A))
A

4


array([[ 9,  2,  4,  3],
       [10,  0,  0, -4],
       [ 7,  5,  0,  3],
       [ 7,  1,  4, -1],
       [ 9,  4,  1, -4]])

Найдите матрицу Грама системы векторов. В качестве ответа запишите элемент из четвёртого столбца первой строки.

In [39]:
G = A.T@A
print('Матрица Грама:\n',G)

Матрица Грама:
 [[360  96  73 -35]
 [ 96  46  16   4]
 [ 73  16  33   4]
 [-35   4   4  51]]


Найдите определитель матрицы Грама. Ответ округлите до целого числа.

In [41]:
print('Определитель матрицы Грама:\n',np.linalg.det(G).round(0))

Определитель матрицы Грама:
 3716648.0


Найдите обратную матрицу к матрице Грама. В качестве ответа запишите элемент из первого столбца третьей строки, округлив его до трёх знаков после точки-разделителя.

In [44]:
inv_G = np.linalg.inv(G)
print('Обратная к матрице Грама:\n',inv_G)
print(inv_G[2,0].round(3))

Обратная к матрице Грама:
 [[ 0.01711488 -0.02798543 -0.02623063  0.01599775]
 [-0.02798543  0.071967    0.03031441 -0.02722776]
 [-0.02623063  0.03031441  0.07683106 -0.02640498]
 [ 0.01599775 -0.02722776 -0.02640498  0.03479318]]
-0.026
