# **Основные понятия линейной алгебры: векторы и действия над ними**

✍ Итак, начнём же наше погружение в линейную алгебру с фундаментального понятия этой науки — **вектора**.

На протяжении курса мы много раз встречались с этим термином. Например, мы часто говорили «вектор-столбец», когда работали с DataFrame, или «вектор параметров» в моделях линейной регрессии. Настало время посмотреть на эту терминологию с формальной точки зрения. Существует множество определений понятия «вектор» в зависимости от контекста.
***
На уроках геометрии в школе вам рассказывали, что ***вектор** — это отрезок, соединяющий две точки в пространстве и имеющий направление.*
***

Например, вектор ![](data/2.PNG) представленный на рисунке ниже, соединяет две точки, А и B. Направление вектора указывается от точки А к точке B.

![](https://lms.skillfactory.ru/assets/courseware/v1/96b4a4ebc0c8d5600159bb9c8dc92bbb/asset-v1:SkillFactory+DSPR-2.0+14JULY2021+type@asset+block/MATHML_md1_2_1.png)

В строгом математическом смысле под **вектором** понимается часть некоторого векторного пространства с множеством различных свойств, но об этом мы поговорим чуть позже.

В Python тоже есть своё понятие вектора, например это одномерный numpy-массив или список из чисел.

Давайте введём наиболее общее определение, которое подойдёт ко всем случаям.
***
***Вектор — это набор чисел, записанных в определённом порядке (в столбец или в строку).***
***
Вектор, состоящий из *m* координат, записывается следующим образом:

![](data/3.PNG)

Примечание. Стрелка наверху  указывает на то, что переменная ***s*** является вектором. Однако нередко в литературе для краткости записи стрелку опускают и записывают просто s = (s1,s2,...sm). Мы будем придерживаться математического формализма и ставить стрелку для обозначения вектора.

Давайте сразу рассмотрим пример из жизни.

Агентство недвижимости «Рай в шалаше» занимается сдачей жилья в аренду. Данные по объектам в одном районе Москвы за последний месяц представлены в таблице ниже.

Столбцы этой таблицы мы можем рассмотреть в качестве векторов, получив информацию о каждой квартире по одному параметру, например по величине арендной платы (вектор s). Если взять в качестве векторов строки таблицы, то мы увидим срез всех параметров по одной квартире (вектор f).

![](https://lms.skillfactory.ru/assets/courseware/v1/6555d51c1d513b28dbae03632c1d3f21/asset-v1:SkillFactory+DSPR-2.0+14JULY2021+type@asset+block/MATHML_md1_2_2.png)

Числа s1,s2,s3 называются координатами вектора, а количество этих координат dim =(s) называется размерностью вектора.

Примечание. Векторы s и f из прошлого примера имели размерности ![](data/4.PNG).
***
Агентство недвижимости выставило за неделю несколько квартир площадью 33, 65, 50 и 45 кв. м. Сколько всего квартир выставлено за неделю? Какова площадь квартиры № 3?

Решим нашу задачу с помощью векторного инструментария. Составим вектор s) из площадей квартир.

Количество квартир равно размерности вектора s. Размерность — количество координат: dim (s) = 4.

Площадь третьей квартиры — это третья координата вектора: s3 =50 м2 

Теперь рассмотрим, что представляет собой вектор в Python.

Рассматриваем ту же самую задачу. Дан вектор ![](data/5.PNG). Необходимо найти его размерность и третью координату.


**1. Вызываем библиотеку numpy, т. к. именно в ней удобнее всего работать с векторами.**

In [1]:
import numpy as np

**2. Задаём вектор s как одномерный массив numpy с помощью функции np.array.**

In [2]:
s = np.array([33, 64, 50, 45])
s

array([33, 64, 50, 45])

**3. Находим третью координату.**

Помним, что в Python массивы нумеруются с нуля, а не с единицы, поэтому для третьей квартиры нужен элемент массива с номером 2.

In [3]:
s[2]

50

**4. Находим размерность вектора. За размерность отвечает функция len().**

In [4]:
len(s)

4

У вас, должно быть, возник вопрос: «Зачем так сложно?!» Зачем мы вводили векторы, их координаты и размерности, а потом даже писали программу, если и так понятно, что количество квартир — 4, а площадь третьей квартиры — 50 м2.

Представьте, что квартир не четыре, а несколько сотен, и вам нужно узнать их точное количество, а также получить параметры квартиры № 151. В таком случае математика будет работать точно так же, как и для случая из четырёх квартир. В этом и состоит прелесть математики: рассматривая частный простой случай, мы почти всегда можем быть уверены, что точно такая же логика сработает и в общем случае.

Примечание. Из описанного выше правила существуют исключения, однако они выходят за рамки нашего курса и используются в основном в приложениях теоретической физики.

![](data/6.PNG)

***
## * **ГЕОМЕТРИЧЕСКАЯ ИНТЕРПРЕТАЦИЯ ВЕКТОРА. ВЕКТОРНОЕ ПРОСТРАНСТВО**

Рядом с линейной алгеброй всегда идёт наука под названием аналитическая геометрия. Поэтому, говоря о векторах, нельзя не упомянуть о его геометрической интерпретации, чтобы создать целостное понимание. Геометрический смысл вектора поможет понять, что такое **векторное пространство**.

Примечание. Приведённая геометрическая интерпретация справедлива как для векторов, записанных в строку, так и для векторов, записанных в столбец.

![](data/7.PNG)

![](https://lms.skillfactory.ru/assets/courseware/v1/de2a565bd8e5ef256e4f053c7969932c/asset-v1:SkillFactory+DSPR-2.0+14JULY2021+type@asset+block/MATHML_md1_2_3.png)

![](data/8.PNG)

→ Таким образом, любой вектор ***s*** размерности 2 можно интерпретировать как направленный отрезок, имеющий конец и начало.

Любой отрезок, даже направленный, имеет длину. Длина вектора s обозначается как |s| и определяется как гипотенуза треугольника p0p1p2 по теореме Пифагора:

![](data/9.PNG)

![](https://lms.skillfactory.ru/assets/courseware/v1/46b835be74d87c8637eedfc53b92e5c4/asset-v1:SkillFactory+DSPR-2.0+14JULY2021+type@asset+block/MATHML_md1_2_4.png)

![](data/10.PNG)

![](https://lms.skillfactory.ru/assets/courseware/v1/d74474371eb44b04f274a7d173743209/asset-v1:SkillFactory+DSPR-2.0+14JULY2021+type@asset+block/MATHML_md1_2_5.png)

Сколько комбинаций точек P1 и P2 можно придумать? Если подумать, бесконечное множество. Получается, существует бесконечное количество векторов s? 

И да, и нет. Если посмотреть на приведённый выше рисунок, можно заметить, что все векторы имеют одинаковую длину |s| = 5, а также параллельны друг другу и имеют одно и то же направление. В этом случае говорят, что **векторы сонаправлены и равны друг другу**. Тогда все векторы можно совместить в один с помощью параллельного переноса в какую-то точку на плоскости. 

В линейной алгебре в качестве такой точки принята точка начала системы координат O = (0,0). Таким образом, начало всех возможных векторов s переносится в точку O и геометрическая интерпретация вектора s размерности 2 обретёт новый смысл.

![](data/11.PNG)

![](https://lms.skillfactory.ru/assets/courseware/v1/94c62d86a00a38d18d264a188115c679/asset-v1:SkillFactory+DSPR-2.0+14JULY2021+type@asset+block/MATHML_md1_2_6.png)

Множество всех возможных векторов S называют векторным пространством.

![](data/12.PNG)

![](https://lms.skillfactory.ru/assets/courseware/v1/7f8a64d27ad34d59a3f8b4056c35ffd9/asset-v1:SkillFactory+DSPR-2.0+14JULY2021+type@asset+block/MATHML_md1_2_7.png)

Длина трёхмерного вектора s определяется аналогично двухмерному:

![](data/13.PNG)

Давайте отойдём от строгой математики и разберём, что собой представляет векторное пространство в нашей жизни.

Вернёмся к примеру с арендой квартир. Пусть у нас есть четыре квартиры, которые характеризуются тремя признаками (арендная плата, площадь, число показов в день), представленными в таблице (привычный нам DataFrame):

![](data/14.PNG)

Примечание. Здесь первый индекс координаты обозначает номер вектора (строка матрицы), а второй индекс — номер его координаты (столбец).

![](data/15.PNG)



***
## **БАЗОВЫЕ ОПЕРАЦИИ С ВЕКТОРАМИ**

Внутри любого векторного пространства должны быть определены следующие операции с векторами:

* Сложение/вычитание векторов. Результат — вектор.
* Умножение вектора на скаляр (число). Результат — вектор.
* Линейная комбинация векторов. Результат — вектор.

***
### **СЛОЖЕНИЕ/ВЫЧИТАНИЕ ВЕКТОРОВ**

Сложение векторов происходит поэлементно: первая координата складывается с первой, вторая — со второй и так далее.

Давайте скажем то же самое на языке линейной алгебры ↓

![](data/16.PNG)

За текущую неделю просмотры по четырём квартирам составили 10, 8, 5 и 1 раз, а за предыдущую — 5, 15, 9 и 7 раз соответственно. Найдите суммарное количество просмотров за две недели. Найдите разницу в просмотрах по каждой квартире за две недели.

![](data/17.PNG)

**Решение на Python**

Сложение и вычитание векторов в Python происходит при помощи знаков + и -. Причём важно задать векторы именно как массивы numpy, а не как обычные списки типа list.

In [5]:
a = np.array([10, 8, 5, 1])
b = np.array([5, 15, 9, 7])
a + b

array([15, 23, 14,  8])

In [6]:
a - b

array([ 5, -7, -4, -6])

***
### **УМНОЖЕНИЕ ВЕКТОРА НА СКАЛЯР**

Умножение вектора на число также происходит поэлементно, то есть каждая координата вектора умножается на заданное число.

Включаем «переводчик» на язык линейной алгебры. 

![](data/18.PNG)

Векторы v1 и v2 пропорциональны друг другу с коэффициентом ω. По-другому такие векторы называются **коллинеарными**. Обозначается: v1||v2.

Если коэффициент пропорциональности положительный (ω>0), векторы сонаправлены (смотрят в одном направлении), если отрицательный (ω<0) — противоположно направлены. Геометрически это значит, что векторы лежат на одной прямой (или параллельных прямых) и направлены в одну или противоположные стороны. О геометрической интерпретации мы поговорим чуть позже.

Пусть агентская комиссия фиксирована и составляет 20 % с каждой сделки. Агент Алексей закрыл три сделки по аренде квартир с арендной платой 120, 45 и 68 тысяч рублей в месяц. Найдите комиссию Алексея за каждую сделку.

![](data/19.PNG)

**Решение на Python**

В Python число умножается на массив numpy обычным оператором умножения.

In [7]:
a = np.array([120, 45, 68])
omega = 0.2
c = a * omega
c

array([24. ,  9. , 13.6])

Нулевые вектора

![](data/20.PNG)

![](data/21.PNG)

In [8]:
a = np.array([120, 150, 190])
b = np.array([130, 130, 130])
c = np.array([2, 3, 2.5])
omega = 72
t = c * omega
s = a+b+t
s

array([394., 496., 500.])

***
## ***ГЕОМЕТРИЧЕСКАЯ ИНТЕРПРЕТАЦИЯ БАЗОВЫХ ОПЕРАЦИЙ С ВЕКТОРАМИ**

Давайте рассмотрим операции сложения и умножения на скаляр с точки зрения геометрии. Рассмотрим двухмерный случай. Пусть есть два вектора:

![](data/22.PNG)

![](https://lms.skillfactory.ru/assets/courseware/v1/182ffe0d514e938ae7c141c03c658f48/asset-v1:SkillFactory+DSPR-2.0+14JULY2021+type@asset+block/MATHML_md1_2_9.png)

Геометрически сложить два вектора v1 и v2 — значит построить **диагональ параллелограмма**, построенного на этих векторах. Эта диагональ параллелограмма и будет вектором v3.

![](data/23.PNG)

Построим векторы на плоскости:

![](https://lms.skillfactory.ru/assets/courseware/v1/d08cb895ec83df595d6e617b16efb1b6/asset-v1:SkillFactory+DSPR-2.0+14JULY2021+type@asset+block/MATHML_md1_2_10.png)

Геометрически умножить вектор на скаляр означает изменить его длину в α раз. 

![](data/24.PNG)

***
## **ЛИНЕЙНАЯ КОМБИНАЦИЯ ВЕКТОРОВ**

**Линейная комбинация** — это объединение операций сложения векторов и умножения на скаляр в одну. Каждый вектор умножается на соответствующий ему коэффициент, все умноженные векторы складываются.

Вновь включаем «переводчик» на язык формальной линейной алгебры.

У риелтора Алексея есть канал в Telegram, где он формирует очередь на показы трёх особенно привлекательных квартир. Premium-показ стоит 500 рублей, VIP-показ — 100 рублей, обычный показ — бесплатно.

За неделю по каждой квартире было 2, 4 и 5 Premium-показов, 8, 10 и 2 VIP-показов и 0, 12 и 7 обычных показов соответственно.

Сколько Алексей заработал на показах по каждой квартире?

Начинаем, как обычно, с записи данных задачи в векторном виде.

![](data/26.PNG)


**Решение на Python**

В Python линейная комбинация полностью соответствует своему названию и вычисляется как комбинация сложения векторов и умножения вектора на число.

Обратите внимание: нулевой коэффициент у вектора обычных показов означает, что фактически он не участвует в линейной комбинации, то есть от количества бесплатных показов заработок Алексея никак не зависит.

In [9]:
p = np.array([2, 4, 5])
v = np.array([8, 10, 2])
s = np.array([0, 12, 7])
omega1 = 500
omega2 = 100
omega3 = 0
u = omega1*p + omega2*v + omega3*s
u

array([1800, 3000, 2700])

**НУЛЕВАЯ ЛИНЕЙНАЯ КОМБИНАЦИЯ**

Самое интересное в линейных комбинациях — это особые случаи, а именно нулевая линейная комбинация. 

Линейная комбинация векторов называется нулевой, если результат линейной комбинации равен нулевому вектору:

![](data/27.PNG)

Как получить нулевой вектор из линейной комбинации? Самый простой вариант — чтобы все коэффициенты линейной комбинации были равны 0. Однако такой случай, называемый **тривиальным**, нам не интересен.

![](data/28.PNG)

Если с тривиальными линейными комбинациями всё понятно, то с нетривиальными нам предстоит долгая и упорная работа, так как они очень важны при работе с регрессиями.

![](data/29.PNG)



**ЛИНЕЙНАЯ (НЕ)ЗАВИСИМОСТЬ**

Предположим, что нам удалось составить нетривиальную комбинацию, то есть удалось подобрать такие ![](data/30.PNG)

В таком случае векторы, из которых была составлена линейная комбинация v1,v2,v3, называются **линейно зависимыми**.

Тогда хотя бы один из векторов, но не обязательно любой, в линейной комбинации можно выразить через другие векторы, представив его как линейную комбинацию.

Или же, возможно, как мы ни старались, но нам не удалось подобрать такие коэффициенты wi<>0, чтобы составить нулевую нетривиальную линейную комбинацию. Такие векторы называются **линейно независимыми**. В таком случае ни один из векторов не выражается через другие векторы.

Давайте посмотрим на линейную (не)зависимость на двух простых примерах.

![](data/31.PNG)

![](data/32.PNG)

Понятие линейной зависимости векторов — одно из главных в линейной алгебре. Мы рассмотрели линейную зависимость на самых простых примерах, где можно подобрать коэффициенты на глаз. 

Конечно же на практике никто не использует подбор коэффициентов, чтобы определить, являются ли векторы линейно зависимыми. Если векторы не целочисленные, а, например, дробные, ручной подбор — очень неприятное и неблагодарное занятие. Существуют специальный критерий определения линейной зависимости, о котором мы поговорим чуть позже, когда познакомимся с системами линейных уравнений и понятием **ранга** матрицы.



***
## **СКАЛЯРНОЕ ПРОИЗВЕДЕНИЕ ВЕКТОРОВ**

Итак, мы научились складывать векторы и умножать их на скаляры. Однако мы ничего не сказали про умножение векторов друг на друга. Нужно это исправить.

Существует четыре способа умножить векторы между собой:

* **Скалярное** произведение. Результат — число. 
* **Векторное** произведение. Результат — вектор.
* **Смешанное** произведение. Результат — число. 
* **Тензорное** произведение. Результат — матрица.

В этом юните мы рассмотрим скалярное произведение, так как именно оно лежит в основе многих операций с векторами в моделях машинного обучения и обладает наибольшей ценностью для нас.

В юните про матричное умножение мы кратко затронем тензорное произведение. Оно нам очень пригодится, когда мы будем знакомиться с глубоким обучением (Deep Learning).
***
*Чтобы найти **скалярное произведение** двух векторов, необходимо перемножить их координаты с одинаковыми номерами и сложить то, что получится.*
***
А теперь переведём это на язык линейной алгебры ↓

![](data/33.PNG)
***

Риелтор Алексей за неделю закрыл четыре сделки по аренде квартир с арендной платой 65, 70, 120 и 30 тысяч рублей. Его комиссии по каждой сделке составили 40 %, 40 %, 20 % и 80 % соответственно.

Сколько Алексей заработал за эти четыре сделки?

Переводим задачу на язык линейной алгебры. Как всегда, сначала запишем данные задачи в векторном виде:

![](data/34.PNG)

Чтобы посчитать заработок Алексея, необходимо каждую координату вектора арендной платы умножить на соответствующую комиссию из вектора комиссий. Тогда заработок Алексея определяется как скалярное произведение векторов v и w.

![](https://lms.skillfactory.ru/assets/courseware/v1/2d3b9f80e7bc6b0f0db2433fb583bfee/asset-v1:SkillFactory+DSPR-2.0+14JULY2021+type@asset+block/MATHML_md1_2_11.png)

![](data/35.PNG)

**Решение на Python**

В Python скалярное произведение векторов вычисляется при помощи функции **np.dot()**:

In [10]:
a = np.array([65, 70, 120, 30])
w = np.array([0.4, 0.4, 0.2, 0.8])
np.dot(a, w)

102.0

**ДЛИНА ВЕКТОРА ЧЕРЕЗ СКАЛЯРНОЕ ПРОИЗВЕДЕНИЕ**

Через скалярное произведение можно выразить длину вектора ![](data/36.PNG)

Ранее мы говорили, что длина вектора определяется по теореме Пифагора как гипотенуза:

![](data/37.PNG)

Таким образом, в линейной алгебре **длина вектора определяется как квадратный корень из скалярного произведения вектора с самим собой**.

![](data/38.PNG)

Длина вектора всегда неотрицательна и показывает, как близок вектор к нулевому.

Вычисление длин векторов в Python мы обсудим в скринкасте в одном из следующих разделов.

**СВОЙСТВА СКАЛЯРНОГО ПРОИЗВЕДЕНИЯ**

Скалярное произведение — это не просто удобная форма записи умножения векторов. На самом деле скалярное произведение обладает рядом очень полезных **свойств**.

![](data/39.PNG)

![](data/40.PNG)

![](data/41.PNG)

![](https://lms.skillfactory.ru/assets/courseware/v1/4cf29e5f89b3a5245ef56d60ad2364c6/asset-v1:SkillFactory+DSPR-2.0+14JULY2021+type@asset+block/MATHML_md1_2_12.png)

Свойство ортогональности векторов применяется для определения линейной зависимости между ними, о которой поговорим чуть позже.

***
## ***ВЕКТОРНАЯ ЗАПИСЬ МОДЕЛИ ЛИНЕЙНОЙ РЕГРЕССИИ**

На самом деле мы уже с вами применяли операцию скалярного произведения векторов. Это было, когда мы вводили уравнение линейной регрессии. Давайте вспомним как оно выглядит. 

![](data/42.PNG)

Пример задачи скалярного произведения

![](data/43.PNG)

![](data/44.PNG)