# **Матричное умножение**

✍ Итак, базовые операции с матрицами мы освоили, и настало время продвинутых.

Начинаем мы с умножения матриц друг на друга и частного случая — умножения вектора на матрицу.

Умножить матрицы между собой — это не значит перемножить элементы между собой. Всё не так просто.

Умножение матриц сильно отличается от умножения простых чисел и обладает совершенно другими свойствами, поэтому мы уделяем этой теме отдельное и особо пристальное внимание. Для начала вам такое умножение покажется непривычным и сложным, но мы постараемся разобраться.

In [1]:
import numpy as np

***
## **ПРОИЗВЕДЕНИЕ ДВУХ МАТРИЦ**

Как обычно, начнём с формул для общего случая, а затем разберём пример.

![](data/69.PNG)

*Важно: умножить матрицу А на матрицу B можно только в том случае, если количество столбцов в матрице А совпадает с количеством строк в матрице B.*

Будем разбирать умножение поэтапно, шаг за шагом.

Итак, чтобы умножить между собой матрицы, необходимо запомнить важную «мантру»: «СЛОЖИТЬ (УМНОЖИТЬ СТРОКА на СТОЛБЕЦ)». То есть, чтобы вычислить элемент cij, нужно умножить строки первой матрицы на столбцы второй и сложить результаты.

![](data/70.PNG)

![](data/71.PNG)

![](data/72.PNG)

![](data/73.PNG)

Результирующая матрица C имеет три строки (как в матрице A) и четыре столбца (как в матрице B).

А теперь попробуем поменять матрицы местами.

![](data/74.PNG)

*Примечание. Попытка умножить матрицы, для которых размерности не равны (n,k) и (k,m) соответственно, — это самая распространённая ошибка новичка. Особенно часто эта ошибка встречается при проектировании нейронных сетей.*

*Как мы позднее увидим, нейронная сеть по своей сути — это простое последовательное умножение большого количества разных матриц разной размерности. Ошибиться в размерности и неправильно умножить матрицы — вполне обычное дело для начинающего DS.*

Рассмотрим другой пример.

![](data/75.PNG)

![](data/76.PNG)

**Отсюда делаем важнейший вывод:**

**Матричное умножение не перестановочно (не коммутативно).** То есть перемена мест сомножителей может привести к различным результатам и даже размерностям.

**Решение на Python**

В Python матрицы можно умножить с помощью функции **np.dot()**. При перемене мест сомножителей результат также меняется.

In [2]:
A = np.matrix("1, -5; 2, 2; 0, 3")
B = np.matrix("3, 1, 0; -1, 0, 2")

In [3]:
A

matrix([[ 1, -5],
        [ 2,  2],
        [ 0,  3]])

In [4]:
B

matrix([[ 3,  1,  0],
        [-1,  0,  2]])

In [5]:
np.dot(A, B)

matrix([[  8,   1, -10],
        [  4,   2,   4],
        [ -3,   0,   6]])

In [6]:
np.dot(B, A)

matrix([[  5, -13],
        [ -1,  11]])

Квадратные матрицы

Мы рассмотрели примеры с прямоугольными матрицами. А что насчёт квадратных матриц? 

С такими матрицами чуть проще. Произведение квадратных матриц существует, когда **порядок обеих матриц совпадает**. Причём результатом умножения квадратных матриц будет квадратная матрица того же порядка, что и исходные.

Например, матрицу 3х3 можно умножить только на матрицу 3х3, но нельзя на матрицу 3х4 или 4х3 или, тем более, 11х23.

Однако равенство результатов при смене мест сомножителей никто не гарантирует. Посмотрим на примере.

![](data/77.PNG)

Мы снова получили несовпадающие результаты и очередное доказательство некоммутативности матриц.

***
## **ПРОИЗВЕДЕНИЕ МАТРИЦЫ И ВЕКТОРА**

Важным для практического применения является частный случай умножения матриц — умножение матрицы на вектор. Так как вектор — это частный случай матрицы размерностью (1,m) или (n,1), то такое умножение полностью подчиняется правилам, которые мы ввели ранее.

*По определению произведения матриц результатом умножения матрицы на вектор всегда получается вектор той же размерности, что и исходный.*

***
                Правило. Вектор-столбец умножается на матрицу справа, а вектор-строка — слева.
***

![](data/78.PNG)

![](data/79.PNG)

***
## **ТЕНЗОРНОЕ ПРОИЗВЕДЕНИЕ ВЕКТОРОВ**

**Тензорное произведение** — это результат матричного умножения вектора-столбца на вектор-строку. Результатом тензорного произведения является матрица.

Рассмотрим пример.

![](data/80.PNG)

Сравним результат тензорного произведения с обычным скалярным произведением векторов:

![](https://lms.skillfactory.ru/assets/courseware/v1/77120415dbece6e119f596cb144de849/asset-v1:SkillFactory+DSPR-2.0+14JULY2021+type@asset+block/MATHML_md1_6_8.png)

В случае скалярного произведения векторов всегда получается число, а в случае тензорного — матрица.

## **Резюмируем общие правила умножения матриц:**

* Число столбцов левой матрицы должно совпадать с числом строк правой матрицы:

![](data/81.PNG)

* Строки левой матрицы скалярно умножаются на столбцы правой матрицы:

![](data/82.PNG)

* Матричное умножение не перестановочно в общем случае:

![](data/83.PNG)

***
## ***ГЕОМЕТРИЧЕСКАЯ ИНТЕРПРЕТАЦИЯ УМНОЖЕНИЯ МАТРИЦЫ НА ВЕКТОР**

Забегая вперёд, скажем, что самом деле операция умножения матрицы на вектор имеет свой тайный геометрический смысл. Мы подробнее с ним познакомимся, когда будем говорить о линейных операторах. Но давайте кратко затронем эту тему.

![](data/84.PNG)

![](https://lms.skillfactory.ru/assets/courseware/v1/c500435b09415df535d8c206af03c9ec/asset-v1:SkillFactory+DSPR-2.0+14JULY2021+type@asset+block/MATHML_md1_6_10.png)

![](data/85.PNG)

Говорят: матрица L задаёт линейный оператор, который действует в векторном пространстве V и переводит векторы в новое векторное пространство U.
***
Мы не будем сейчас подробно вдаваться в тему отображений, так как на эту тему можно создать отдельный курс, однако отметим два интересных частных случая **операторов**, которые активно используются в обработке изображений.

**Оператор сжатия/растяжения:**

![](https://lms.skillfactory.ru/assets/courseware/v1/2bda26c2894a23d8ea0102d681f85983/asset-v1:SkillFactory+DSPR-2.0+14JULY2021+type@asset+block/MATHML_md1_6_11.png)

![](data/86.PNG)

**Оператор поворота:**

![](https://lms.skillfactory.ru/assets/courseware/v1/ceecfca0ba4c1f02a03065249bc02617/asset-v1:SkillFactory+DSPR-2.0+14JULY2021+type@asset+block/MATHML_md1_6_12.png)

![](data/87.PNG)

***
## **УМНОЖЕНИЕ НА СПЕЦИАЛЬНЫЕ МАТРИЦЫ**