# **Практика: матричное умножение**

In [61]:
import numpy as np
import pandas as pd

In [30]:
# произведение матриц
A=np.random.randint(5, 12, (3,3))
B=np.random.randint(-2, 4, (3,3))

In [31]:
A

array([[11, 10,  6],
       [ 5, 11,  7],
       [ 7, 11,  7]])

In [32]:
B

array([[-1,  0,  0],
       [-1,  2,  0],
       [ 1, -2,  1]])

In [33]:
# Поэлементное умножение
A*B

array([[-11,   0,   0],
       [ -5,  22,   0],
       [  7, -22,   7]])

In [34]:
# тип np.matrix
A_m=np.matrix(A)
B_m=np.matrix(B)
print(A_m*B_m)

[[-15   8   6]
 [ -9   8   7]
 [-11   8   7]]


In [35]:
# Матричное умножение
np.dot(A,B)

array([[-15,   8,   6],
       [ -9,   8,   7],
       [-11,   8,   7]])

In [36]:
# Матричное умножение
A@B

array([[-15,   8,   6],
       [ -9,   8,   7],
       [-11,   8,   7]])

In [37]:
# Порядок умножения AB != BA
B@A

array([[-11, -10,  -6],
       [ -1,  12,   8],
       [  8,  -1,  -1]])

In [38]:
# Умножение прямоугольных матриц возможно не в любом порядке
A=np.random.randint(5, 12, (3,5))
B=np.random.randint(-2, 4, (5,2))
print('A:\n',A)
print('B:\n',B)

A:
 [[11  5  6  5 10]
 [10  9  9  8  8]
 [11 10  7  6  8]]
B:
 [[ 2  3]
 [-2 -1]
 [ 2 -1]
 [ 2  3]
 [ 2 -1]]


In [39]:
# Умножение прямоугольных матриц возможно не в любом порядке
A@B

array([[54, 27],
       [52, 28],
       [44, 26]])

In [40]:
# Умножение прямоугольных матриц возможно не в любом порядке
#B@A

In [41]:
# размер произведения матриц
print('shape of A:', np.shape(A))
print('shape of B:', np.shape(B))
print('shape of AB:', np.shape(A@B))

shape of A: (3, 5)
shape of B: (5, 2)
shape of AB: (3, 2)


In [42]:
# умножение на специальные матрицы
A=np.random.randint(-4, 4, (4,4))
D=np.diag([1,2,0,-1])
print('A:\n',A)
print('D:\n',D)
print('AD:\n',A@D)
print('DA:\n',D@A)

A:
 [[-1  2  2 -2]
 [-1 -2  1 -4]
 [ 2 -4 -4  0]
 [ 3  1 -4 -2]]
D:
 [[ 1  0  0  0]
 [ 0  2  0  0]
 [ 0  0  0  0]
 [ 0  0  0 -1]]
AD:
 [[-1  4  0  2]
 [-1 -4  0  4]
 [ 2 -8  0  0]
 [ 3  2  0  2]]
DA:
 [[-1  2  2 -2]
 [-2 -4  2 -8]
 [ 0  0  0  0]
 [-3 -1  4  2]]


In [43]:
# умножение на одномерный массив numpy
A=np.array([[1,0,1],[1,1,1]])
b=np.array([-3,4,5])
A@b

array([2, 6])

In [44]:
#b@A

In [45]:
# матрица Грама ортогональной системы векторов
x=np.array([1,1,1])
y=np.array([1,0,-1])
z=np.array([-1,2,-1])
A=np.array([x,y,z])
print (A, type(A))

[[ 1  1  1]
 [ 1  0 -1]
 [-1  2 -1]] <class 'numpy.ndarray'>


In [46]:
# матрица Грама ортогональной системы векторов
A@A.T

array([[3, 0, 0],
       [0, 2, 0],
       [0, 0, 6]])

In [47]:
# матрица Грама ортонормированной системы векторов
x_norm=x/np.linalg.norm(x)
y_norm=y/np.linalg.norm(y)
z_norm=z/np.linalg.norm(z)
A_norm=np.array([x_norm,y_norm,z_norm])
print (A_norm, type(A_norm))

[[ 0.57735027  0.57735027  0.57735027]
 [ 0.70710678  0.         -0.70710678]
 [-0.40824829  0.81649658 -0.40824829]] <class 'numpy.ndarray'>


In [48]:
# матрица Грама ортонормированной системы векторов
A_norm@A_norm.T

array([[ 1.00000000e+00, -1.77961928e-17,  1.66584120e-17],
       [-1.77961928e-17,  1.00000000e+00, -2.45142679e-17],
       [ 1.66584120e-17, -2.45142679e-17,  1.00000000e+00]])

In [49]:
# ортонормированные системы рулят! :)
np.round(A_norm@A_norm.T,1)

array([[ 1., -0.,  0.],
       [-0.,  1., -0.],
       [ 0., -0.,  1.]])

Даны матрица A и вектор х:

Найдите произведение матрицы  и вектора х в том порядке, в котором их можно умножить.

В качестве ответа запишите координаты получившегося вектора через запятую, без пробелов. Пример ввода ответа: 1,1.

In [51]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])

A@x

array([26, 30])

Даны две матрицы:

Найдите произведение матриц A и B в том порядке, в котором их можно умножить.

В качестве ответа через запятую, без пробелов запишите элемент чётвертого столбца первой строки.

In [55]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])

B@A

array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

Дана система векторов:

Составьте матрицу A, расположив векторы x, y, z в строках. Найдите матрицу Грама G системы векторов x, y, z.

Чему равна полученная матрица Грама ?

In [58]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

A=np.array([x,y,z])
print (A, type(A))
print(A.T@A)

[[ 1  2  1  0  4]
 [ 2  1 -1  1  0]
 [-1  1 -1  0  0]] <class 'numpy.ndarray'>
[[ 6  3  0  2  4]
 [ 3  6  0  1  8]
 [ 0  0  3 -1  4]
 [ 2  1 -1  1  0]
 [ 4  8  4  0 16]]


В салоне красоты «Феи ножниц» работают восемь стилистов: Аня, Борис, Вика, Галя, Дима, Егор, Женя и Юра. 

Вам предоставлены две таблицы (DataFrame): Count_DF и Price_DF.

* В DataFrame Count_DF содержится информация по количеству услуг, оказанных каждым стилистом за апрель.

* В DataFrame Price_DF содержится информация по стоимости услуг у каждого стилиста в тысячах рублей.

In [62]:
Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)

Найдите вектор прибыли салона по стилистам, если за каждую услугу стилисты платят салону определённую комиссию.

Вектор комиссий: com = np.array([0.2, 0.2, 0.3, 0.1, 0.1]).

Выберите координаты вектора прибыли салона:

In [69]:
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])

Count_DF*Price_DF@com.T

Аня      11.30
Борис    15.22
Вика     11.90
Галя     20.60
Дима     41.90
Егор     21.20
Женя     11.49
Юра      38.25
dtype: float64

Найдите вектор прибыли стилистов.

Выберите координаты полученного вектора:

In [75]:
income = 1-com

Count_DF*Price_DF@income.T

Аня       50.20
Борис     74.88
Вика      59.10
Галя      67.80
Дима     166.60
Егор     113.80
Женя      66.21
Юра      157.75
dtype: float64