# **Обратная матрица. Определитель матрицы**

✍ Ранее мы научились умножать матрицы между собой. Однако возникает вопрос: можно ли **делить** матрицы друг на друга? В этом юните мы постараемся на него ответить.

In [1]:
import numpy as np

## **ОБРАТНАЯ МАТРИЦА**

Для того чтобы ввести понятие **обратной матрицы**, давайте ненадолго вернёмся в одномерное пространство и поговорим не о двумерных матрицах, а о числах.

Из школьного курса алгебры известно, что операция деления числа a на число b — это на самом деле умножение числа a на число, обратное a.
***
**Обратным** к числу a называется такое число a^-1, которое в произведении с числом a даёт 1:

![](data/97.PNG)
***

![](data/98.PNG)

* **Обратные числа есть у всех чисел, кроме нуля**. Запомним это. Данная аналогия нам очень пригодится в работе с матрицами.
* **Обратное число всегда одно**, и **неважно, с какой стороны на него умножать**. 
* Только для **квадратных** матриц существуют обратные

![](data/99.PNG)

Теперь, когда мы вспомнили школьную алгебру, давайте вернёмся к линейной алгебре и обобщим теорию обратных чисел на матрицы, введя понятие обратной матрицы. Сразу оговоримся, что мы будем рассматривать только квадратные матрицы, так как только для них существуют обратные.

Итак, как вы уже догадались, в матричной алгебре в роли единицы выступает единичная матрица E:

![](data/100.PNG)

* **Обратной** к матрице A порядка n называется такая матрица A^-1 порядка n, которая в произведении с матрицей A даёт единичную матрицу. 

Перед нами встаёт задача научиться подбирать такую матрицу, которая даст в произведении с исходной единичную.

Сразу возникают вопросы:

* С какой стороны умножать матрицы: A * A^-1 или A^-1 * A? Ведь мы знаем, что умножение матриц некоммутативно.
* Когда существует матрица A^-1? Бывают ли такие случаи, что обратной матрицы не существует?
* Единственность A^-1. Сколько существует обратных матриц?
* Как считать A^-1?
***

Пример № 1

![](data/101.PNG)

**Произведение матрицы и обратной к ней является перестановочным (коммутативным).**

***

Пример № 2

![](data/102.PNG)

***

Пример № 3

![](data/103.PNG)

Из последнего примера делаем вывод, что **обратная матрица существует не всегда**. Хотелось бы иметь под рукой конкретный критерий, который без лишних манипуляций показал бы, существует ли обратная матрица. Такой критерий есть, и мы поговорим о нём далее.

***

А пока разберёмся с расчётом обратной матрицы. Для случая матрицы 2x2 обратная матрица считается очень просто:

![](data/104.PNG)

Рассмотрим пример.

![](data/105.PNG)

Если для простейших матриц 2x2 ручной поиск обратной матрицы не составляет особого труда, то про матрицы большего порядка сказать так уже нельзя.

В общем случае алгоритм вычисления обратной матрицы n*n очень громоздкий и сложный. Обычно его изучают в университетах, но мы не станем этого делать, так как это не имеет смысла — если перед вами встанет задача вычисления обратной матрицы, вы в основном будете пользоваться инструментами Python.

**Решение на Python**

Обратная матрица в Python вычисляется с помощью функции **numpy.linalg.inv()**:

In [3]:
A = np.matrix('1,2,3; 4,5,6; 7,8,10')
print(A)

np.linalg.inv(A)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]


matrix([[-0.66666667, -1.33333333,  1.        ],
        [-0.66666667,  3.66666667, -2.        ],
        [ 1.        , -2.        ,  1.        ]])

Мы с вами ответили на три вопроса из четырёх: выяснили, что обратная матрица единственна, произведение матрицы на обратную даёт единичную как слева направо, так и справа налево, а также научились считать простейшие обратные матрицы вручную и в Python.

Остался открытым вопрос о существовании обратной матрицы. Для введения критерия существования матрицы для общего случая нам необходимо познакомиться с таким термином как «определитель матрицы». 

Также мы ответили на главный вопрос юнита: **можно ли делить матрицы друг на друга.** Да, можно. Разделить матрицу B на матрицу A означает умножить B на A^-1.



In [5]:
A = np.matrix('1,2; 2,5')
print(A)

np.linalg.inv(A)

[[1 2]
 [2 5]]


matrix([[ 5., -2.],
        [-2.,  1.]])

***
## **ОПРЕДЕЛИТЕЛЬ МАТРИЦЫ**

            Определитель матрицы — это специальная числовая характеристика
            квадратных матриц, которая является своего рода мерой вырожденности
            матрицы: чем ближе определитель к нулю, тем хуже работают
            стандартные численные алгоритмы для вычисления обратных матриц.

Обозначение:  det (A) или |A|

Примечание. У определителя также имеется и геометрический смысл. Модуль определителя равен объёму n-мерного параллелепипеда, натянутого на столбцы матрицы.

**РАСЧЁТ ОПРЕДЕЛИТЕЛЯ**

В простейшем случае матрицы 2x2 для расчёта определителя необходимо просто перемножить элементы главной и побочной диагоналей и вычесть второе из первого.

![](data/106.PNG)

В общем случае всё сложнее. Для определителей матриц размера 3x3 ещё существуют наглядные, но уже громоздкие формулы, например метод треугольников, с которым вы можете ознакомиться здесь. Однако для матриц порядка больше 3 необходимо применять специальные методы расчёта. Ручной счёт определителей занимает много времени, сил и места на бумаге, а операция расчёта определителя используется очень часто.

![](data/107.PNG)

В Python определитель считается с помощью функции **np.linalg.det()**.

**Решение на Python**

![](data/108.PNG)

In [6]:
import numpy as np
A = np.matrix ("1, 2, 3; 4, 5, 6 ; 7, 8, 10")
print(np.linalg.det(A))

-2.9999999999999996


**СВОЙСТВА ОПРЕДЕЛИТЕЛЯ**

У определителя есть множество полезных свойств. Вот некоторые из них

* **Определитель единичной матрицы предсказуемо равен единице:**

![](data/109.PNG)

* **Для диагональной матрицы определитель равен произведению диагональных элементов:**

![](data/110.PNG)

* **При умножении матрицы на константу β определитель увеличивается в β^n раз, где n — порядок матрицы:**

![](data/111.PNG)

* **При транспонировании определитель матрицы не изменяется:**

![](data/112.PNG)

* **Определитель произведения матриц A и B равен произведению определителей этих матриц и не зависит от порядка умножения:**

![](data/113.PNG)

* **Из последнего свойства определителя получается связь определителей матрицы и соответствующей ей обратной матрицы: их произведение равно единице.**

![](data/114.PNG)

Таким образом, определитель обратной матрицы A равен 1/det(A) в случае, если определитель матрицы А не равен нулю.

**ВЫРОЖДЕННОСТЬ МАТРИЦ**

                Матрица A называется вырожденной, если её определитель равен 0:

![](data/115.PNG)

Для **вырожденных матриц не существует обратных матриц**, так как в противном случае пришлось бы делить на 0 при подсчёте. Строки и столбцы такой матрицы являются линейно зависимыми и выражаются друг через друга. Об этом мы поговорим в следующем юните.

Однако полностью вырожденные матрицы существуют только в теории. На практике мы сталкиваемся с матрицами, близкими к вырожденным. Определитель таких матриц не равен 0, но близок к нему (например, равен 10^-5):

При компьютерных вычислениях такие матрицы могут спровоцировать неприятности: они являются триггером для большого количества вычислительных ошибок, так как при вычислении обратной матрицы мы будем вынуждены делить на определитель det(A). Деление на число, близкое к 0, не выдаст нам ошибки, мы даже этого не заметим, однако элементы обратной матрицы A^-1 будут стремиться к бесконечности. 

Вспомните: мы с вами уже сталкивались с этой проблемой в модуле ML-2 «Обучение с учителем. Задача регрессии», когда учились строить линейную регрессию. В одном из примеров у нас внезапно получились огромные коэффициенты линейной регрессии, которые стремились к бесконечности. Это и есть последствия обращения вырожденных матриц при построении моделей.

С этой проблемой справляются с помощью знакомых нам **методов регуляризации**. Подробнее о них мы поговорим в следующем модуле.

In [12]:
A = np.matrix('2,0,0; 0,1,0; 0,0,4')
A_inv = np.linalg.inv(A)
print(np.linalg.det(A))
print(np.linalg.det(A_inv).round(3))

7.999999999999998
0.125
